# -*- Pyrex -*-
#
# ======================================================================
#
#                           Brad T. Aagaard
#                        U.S. Geological Survey
#
# {LicenseText}
#
# ======================================================================
#

#header{
#include "pylith/meshio/MeshIO.hh"
#include "pylith/meshio/MeshIOAscii.hh"

#include <stdexcept>
#include <assert.h>
#include <Python.h>
#}header

# ----------------------------------------------------------------------
cdef extern from "Python.h":
  object PyCObject_FromVoidPtr(void*, void (*destruct)(void*))
  void* PyCObject_AsVoidPtr(object)

cdef void* ptrFromHandle(obj):
  """Extract pointer from PyCObject."""
  return PyCObject_AsVoidPtr(obj.handle)

cdef extern from "stdlib.h":
    ctypedef unsigned long size_t
    void* malloc(size_t size)
    void free(void* mem)

# ----------------------------------------------------------------------
cdef class MeshIO:

  cdef void* thisptr # Pointer to C++ object
  cdef readonly object handle # PyCObject holding pointer to C++ object
  cdef readonly object name # Identifier for object base type

  def __init__(self):
    """
    Constructor.
    """
    self.handle = None
    self.thisptr = NULL
    self.name = "pylith_meshio_MeshIO"
    return


  def read(self, mesh):
    """
    Read mesh from file.
    """
    # create shim for method 'read'
    #embed{ void MeshIO_read(void* pObj, void* pMeshObj)
    try {
      assert(0 != pObj);
      assert(0 != pMeshObj);
      ALE::Obj<ALE::Mesh>* pMesh = (ALE::Obj<ALE::Mesh>*) pMeshObj;
      ((pylith::meshio::MeshIO*) pObj)->read(pMesh);
    } catch (const std::exception& err) {
      PyErr_SetString(PyExc_RuntimeError,
                      const_cast<char*>(err.what()));
    } catch (...) {
      PyErr_SetString(PyExc_RuntimeError,
                      "Caught unknown C++ exception.");
    } // try/catch
    #}embed

    #cdef topology.Mesh mesh
    MeshIO_read(self.thisptr, ptrFromHandle(mesh))
    return


  def write(self, mesh):
    """
    Read write to file.
    """
    # create shim for method 'write'
    #embed{ void MeshIO_write(void* pObj, void* pMeshObj)
    try {
      ALE::Obj<ALE::Mesh>* pMesh = (ALE::Obj<ALE::Mesh>*) pMeshObj;
      ((pylith::meshio::MeshIO*) pObj)->write(pMesh);
    } catch (const std::exception& err) {
      PyErr_SetString(PyExc_RuntimeError,
                      const_cast<char*>(err.what()));
    } catch (...) {
      PyErr_SetString(PyExc_RuntimeError,
                      "Caught unknown C++ exception.");
    } // try/catch
    #}embed
    MeshIO_write(self.thisptr, ptrFromHandle(mesh))
    return


  def _createHandle(self):
    """Wrap pointer to C++ object in PyCObject."""
    # create shim for destructor
    #embed{ void MeshIO_destructor(void* pObj)
    try {
      pylith::meshio::MeshIO* pMesh = (pylith::meshio::MeshIO*) pObj;
      delete pMesh;
    } catch (const std::exception& err) {
      PyErr_SetString(PyExc_RuntimeError,
                      const_cast<char*>(err.what()));
    } catch (...) {
      PyErr_SetString(PyExc_RuntimeError,
                      "Caught unknown C++ exception.");
    } // try/catch
    #}embed
    return PyCObject_FromVoidPtr(self.thisptr, MeshIO_destructor)


  property interpolate:
    def __set__(self, flag):
      """Set interpolate."""
      # create shim for method 'interpolate'
      #embed{ void MeshIO_interpolate_set(void* pObj, int flag)
      try {
        ((pylith::meshio::MeshIO*) pObj)->interpolate(flag);
      } catch (const std::exception& err) {
        PyErr_SetString(PyExc_RuntimeError,
                        const_cast<char*>(err.what()));
      } catch (...) {
        PyErr_SetString(PyExc_RuntimeError,
                        "Caught unknown C++ exception.");
      } // try/catch
      #}embed
      MeshIO_interpolate_set(self.thisptr, flag)

    def __get__(self):
      """Get interpolate."""
      # create shim for method 'interpolate'
      #embed{ int MeshIO_interpolate_get(void* pObj)
      int result = 0;
      try {
        result = ((pylith::meshio::MeshIO*) pObj)->interpolate();
      } catch (const std::exception& err) {
        PyErr_SetString(PyExc_RuntimeError,
                        const_cast<char*>(err.what()));
      } catch (...) {
        PyErr_SetString(PyExc_RuntimeError,
                        "Caught unknown C++ exception.");
      } // try/catch
      return result;
      #}embed
      return MeshIO_interpolate_get(self.thisptr)


# ----------------------------------------------------------------------
cdef class MeshIOAscii(MeshIO):

  def __init__(self):
    """Constructor."""
    # create shim for constructor
    #embed{ void* MeshIOAscii_constructor()
    void* result = 0;
    try {
      result = (void*)(new pylith::meshio::MeshIOAscii);
    } catch (const std::exception& err) {
      PyErr_SetString(PyExc_RuntimeError,
                      const_cast<char*>(err.what()));
    } catch (...) {
      PyErr_SetString(PyExc_RuntimeError,
                      "Caught unknown C++ exception.");
    } // try/catch
    return result;
    #}embed

    MeshIO.__init__(self)
    self.thisptr = MeshIOAscii_constructor()
    self.handle = self._createHandle()
    return


  property filename:
    def __set__(self, name):
      """Set filename."""
      # create shim for method 'filename'
      #embed{ void MeshIOAscii_filename_set(void* pObj, char* name)
      try {
        ((pylith::meshio::MeshIOAscii*) pObj)->filename(name);
      } catch (const std::exception& err) {
        PyErr_SetString(PyExc_RuntimeError,
                        const_cast<char*>(err.what()));
      } catch (...) {
        PyErr_SetString(PyExc_RuntimeError,
                        "Caught unknown C++ exception.");
      } // try/catch
      #}embed
      MeshIOAscii_filename_set(self.thisptr, name)

    def __get__(self):
      """Get filename."""
      # create shim for method 'filename'
      #embed{ char* MeshIOAscii_filename_get(void* pObj)
      char* result = 0;
      try {
        result = (char*) ((pylith::meshio::MeshIOAscii*) pObj)->filename();
      } catch (const std::exception& err) {
        PyErr_SetString(PyExc_RuntimeError,
                        const_cast<char*>(err.what()));
      } catch (...) {
        PyErr_SetString(PyExc_RuntimeError,
                        "Caught unknown C++ exception.");
      } // try/catch
      return result;
      #}embed
      return MeshIOAscii_filename_get(self.thisptr)


# End of file 
